[tool.poetry]
name = "slidge"
version = "0.0.0-dev"
description = "XMPP bridging framework"
authors = ["Nicolas Cedilnik <nicoco@nicoco.fr>"]
readme = "README.md"
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
slixmpp = "^1.8.2"
qrcode = ">=7.3"
Pillow = ">=8.1.0"
aiohttp = ">=3.8.1"
ConfigArgParse = "^1.5.3"

aiotdlib = { version = "^0.19.2", optional = true }
pydantic = { version = "*", optional = true }
nextcord = { version = "^2.0.0-alpha.10", optional = true }
aiosignald = { version = "^0.2.1", optional = true }
mautrix-facebook = { version = "^0.4.0", optional = true }
mattermostdriver = { version = "^7.3.2", optional = true }
SkPy = { version =  "^0.10.4", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "*"
black = "*"
Sphinx = "^4"
Pygments = "^2.8.0"
sphinx-rtd-theme = "^1.0.0"
sphinx-argparse = "^0.3.1"
sphinx-autoapi = "^1.8.4"
mypy = "^0.961"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
telegram = ["aiotdlib", "pydantic"]
discord = ["nextcord"]
signal = ["aiosignald"]
facebook = ["mautrix-facebook"]
mattermost = ["mattermostdriver"]
skype = ["SkPy"]

[tool.poetry.scripts]
slidge = 'slidge.__main__:main'

[tool.mypy]
exclude = "slixpatch.py"
ignore_missing_imports = true

[tool.black]
exclude = "xep_*"