[tool.poetry]
name = "slidge"
version = "0.0.0-dev"
description = "XMPP bridging framework"
authors = ["Nicolas Cedilnik <nicoco@nicoco.fr>"]
readme = "README.md"
license = "AGPL-3.0-or-later"
homepage = "https://sr.ht/~nicoco/slidge/"
include = [
    {path = "slidge/plugins/whatsapp/generated/*.py", format = "wheel"},
    {path = "slidge/plugins/whatsapp/generated/*.so", format = "wheel"}
]

[tool.poetry.build]
script = "dev/build.py"
generate-setup-file = false

[tool.poetry.dependencies]
python = "^3.9"
slixmpp = "^1.8.3"
qrcode = ">=7.4.1"
Pillow = ">=8.1.0"
aiohttp = "^3.8.3"
ConfigArgParse = "^1.5.3"

aiotdlib = [
    {url = "https://slidge.im/aiotdlib-0.19.2-cp39-cp39-manylinux_2_31_x86_64.whl", markers = "sys_platform == 'linux' and platform_machine == 'x86_64'", optional = true },
    {url = "https://slidge.im/aiotdlib-0.19.2-cp39-cp39-manylinux_2_31_aarch64.whl", markers = "sys_platform == 'linux' and platform_machine == 'aarch64'", optional = true },
    {url = "https://slidge.im/aiotdlib-0.19.2-cp39-cp39-manylinux_2_31_i686.whl", markers = "sys_platform == 'linux' and platform_machine == 'i686'", optional = true}
]
pydantic = { version = "*", optional = true }
aiosignald = { version = "^0.3.6", optional = true }
mautrix-facebook = { version = "^0.4.1", optional = true }
mattermost-api-reference-client = { version =  "^4.0.0.post1", optional = true }
emoji = { version =  "^2.0.0", optional = true }
SkPy = { version =  "^0.10.4", optional = true }
steam = {extras = ["client"], version = "^1.4.4", optional = true }
"discord.py-self" = { git = "https://github.com/dolfies/discord.py-self.git", rev = "5cfd544", extras = ["speed"], optional = true }
pickle-secure = "^0.99.9"
python-magic = "^0.4.27"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-asyncio = "*"
black = { version = "*", extras = ["d"] }
Sphinx = "^6"
Pygments = "^2.8.0"
sphinx-argparse = "^0.4.0"
sphinx-autoapi = "^2.0.0"
furo = "^2022.6.21"
mypy = "^1.1.1"
types-requests = "^2.28.1"
isort = "^5.11.4"
types-emoji = "^2.0.0"
pybindgen = "^0.22.1"

[build-system]
requires = ["poetry-core>=1.0.0", "pybindgen>=0.22.1"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
telegram = ["aiotdlib", "pydantic"]
discord = ["discord.py-self"]
signal = ["aiosignald"]
facebook = ["mautrix-facebook"]
mattermost = ["mattermost-api-reference-client", "emoji"]
skype = ["SkPy"]
steam = ["steam", "asyncio-gevent"]

[tool.poetry.scripts]
slidge = 'slidge.__main__:main'

[tool.mypy]
exclude = ["slidge.util.xep*", "slidge/plugins/whatsapp/generated"]
ignore_missing_imports = true
check_untyped_defs = true

[tool.black]
exclude = "xep_*|slidge/plugins/whatsapp/generated/*"

